#ifndef COLOURS_H_INCLUDED
#define COLOURS_H_INCLUDED

#define ANSI_DEFAULT_COLOUR  "\033[0m"
#define ANSI_YELLOW          "\033[33m"
#define ANSI_MAGENTA         "\033[35m"
#define ANSI_LIGHT_RED       "\033[91m"
#define ANSI_LIGHT_GREEN     "\033[92m"
#define ANSI_LIGHT_YELLOW    "\033[93m"
#define ANSI_LIGHT_BLUE      "\033[94m"
#define ANSI_LIGHT_CYAN      "\033[96m"

#define YELLOW(s)     ANSI_YELLOW         s ANSI_DEFAULT_COLOUR
#define LRED(s)       ANSI_LIGHT_RED      s ANSI_DEFAULT_COLOUR
#define LGREEN(s)     ANSI_LIGHT_GREEN    s ANSI_DEFAULT_COLOUR
#define LYELLOW(s)    ANSI_LIGHT_YELLOW   s ANSI_DEFAULT_COLOUR
#define LBLUE(s)      ANSI_LIGHT_BLUE     s ANSI_DEFAULT_COLOUR
#define LCYAN(s)      ANSI_LIGHT_CYAN     s ANSI_DEFAULT_COLOUR
#define MAGENTA(s)    ANSI_MAGENTA        s ANSI_DEFAULT_COLOUR

#endif // COLOURS_H_INCLUDED